### ISSUE TITLE
PyTorch implementation for RF/XGB

### ISSUE THREAD

**Issue by jaimergp** [openkinome/kinoml#17]
Some resources:

* Write the model in `sklearn` / `xgboost` and convert to PyTorch: https://towardsdatascience.com/transform-your-ml-model-to-pytorch-with-hummingbird-da49665497e7 (https://github.com/microsoft/hummingbird)
* Use a native PyTorch tree implementation: https://github.com/ValentinFigue/Sklearn_PyTorch

**Comment by jaimergp** [comment]
I have imported `sklearn_pytorch` in our symbols for now.

**Comment by t-kimber** [comment]
I created a new PR (see #25) which deals with the XBGoost package (not sure the _native PyTorch tree implementation_ linked above is flexible enough for the observation models).

**Comment by t-kimber** [comment]
Closing issue since focusing on deep learning models.
