### ISSUE TITLE
kinoml installation

### ISSUE THREAD

**Issue by t-kimber** [openkinome/kinoml#24]
1. Create conda environment using the yaml file
`conda env create --file devtools/conda-envs/test_env.yaml`
2. Activate conda environment
`conda activate test`
3. Install kinoml
`pip install -e . --no-deps`

If, while running the example notebook (see `kinoml/examples/ChEMBL.ipynb`), the following error occurs:
`AttributeError: 'Molecule' object has no attribute 'components'`
in terminal, execute: 
`pip install https://github.com/openforcefield/openforcefield/archive/toolkit-inheritance.zip --no-deps`

**Comment by jaimergp** [comment]
Ideally, force remove `openforcefield` first:

```
conda remove --force openforcefield
pip install -U https://github.com/openforcefield/openforcefield/archive/toolkit-inheritance.zip --no-deps
```
