### ISSUE TITLE
PyTorch & Python 3.9 won't work together

### ISSUE THREAD

**Issue by jaimergp** [openkinome/kinoml#41]
We have disabled Python 3.9 testing because:

* On Linux, it won't install properly
* On MacOS, it will install, but the kernel will die immediately if you try `import kinoml`

We are using PyPI builds for PyTorch because conda-forge's won't work with `torch-geometric`. Until Geometric is on CF, there's no other way around!

**Comment by schallerdavid** [comment]
add MacOS, Python 3.9 to tests
