### ISSUE TITLE
Add structure-based object model based on MDAnalysis to replace PDB artifacts

### ISSUE THREAD

**Issue by schallerdavid** [openkinome/kinoml#80]
Add structure-based object model based on MDAnalysis to replace PDB artifacts.
 - ~serialzation of mda.Universe currently only available in unstable [release](https://pypi.org/project/MDAnalysis/2.0.0b0/)~
 - mdanalysis 2.0.0 available on conda-forge

**Comment by IAlibay** [comment]
> serialzation of mda.Universe currently only available in unstable release

It's out now :)
